version: "3.9"

services:
    app:
        container_name: app
        image: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000" 